[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
board_build.embed_files =
    assets/admin.html
    assets/asc16_printable.bin
    assets/gb2312_level1_16.bin
    assets/gb2312_level1_unicode_map.bin
build_flags =
    -Wall
    -Wextra
